version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - redis #
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - new_network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - new_network

networks:
  new_network:

volumes:
  redis_data:
