version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - redis
      - prometheus
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - new_network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - new_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - new_network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

networks:
  new_network:

volumes:
  redis_data:
